export const colorPalettes = [
	{
		name: "Vermelho",
		primary: "#D7263D",
		secondary: "#971f1f",
		accent: "#292929",
		background: "#FFFAFA",
		text_primary: "#5A1A1A",
		text_secondary: "#333333",
		text_third: "#fff",
		font_primary: "'Poppins', sans-serif",
		font_secondary: "'Roboto', sans-serif",
		color_adm: '#f2f2f2',
		color_text: '#333',

		page_construct_background: '#000',
		page_construct_color: '#fff',
		page_construct_accent: '#ED3237'
	},
	{
		name: "Amarelo",
		primary: "#ffa700",
		secondary: "#ff9b03",
		accent: "#0d476a",
		background: "#FFFEF7",
		text_primary: "#7B6000",
		text_secondary: "#292929",
		text_third: "#ffffff",
		font_primary: "'Nunito', sans-serif",
		font_secondary: "'Open Sans', sans-serif",
		color_adm: '#f2f2f2',
		color_text: '#333',

		page_construct_background: '#000',
		page_construct_color: '#fff',
		page_construct_accent: '#ED3237'
	},
	{
		name: "Preto",
		primary: "#121212",
		secondary: "#2C2C2C",
		accent: "#565656",
		background: "#F7F7F7",
		text_primary: "#333",
		text_secondary: "#333333",
		text_third: "#fff",
		font_primary: "'Montserrat', sans-serif",
		font_secondary: "'Helvetica Neue', sans-serif",
		color_adm: '#f2f2f2',
		color_text: '#333',

		page_construct_background: '#000',
		page_construct_color: '#fff',
		page_construct_accent: '#ED3237'
	},

	{
		name: "Azul",
		primary: "#273db1",
		secondary: "#2196f3",
		accent: "#2f3450",
		background: "#F9FBFF",
		text_primary: "#0D47A1",
		text_secondary: "#292929",
		text_third: "#fff",
		font_primary: "'Roboto', sans-serif",
		font_secondary: "'Open Sans', sans-serif",
		color_adm: '#f2f2f2',
		color_text: '#333',

		page_construct_background: '#000',
		page_construct_color: '#fff',
		page_construct_accent: '#ED3237'
	},
	{
		name: "Roxo",
		primary: "#6A1B9A",
		secondary: "#AB47BC",
		accent: "#2b262c",
		background: "#FBF7FC",
		text_primary: "#4A148C",
		text_secondary: "#292929",
		text_third: "#fff",
		font_primary: "'Raleway', sans-serif",
		font_secondary: "'Lato', sans-serif",
		color_adm: '#f2f2f2',
		color_text: '#333',

		page_construct_background: '#000',
		page_construct_color: '#fff',
		page_construct_accent: '#ED3237'
	},
	{
		name: "Rosa",
		primary: "#EC407A",
		secondary: "#F8BBD0",
		accent: "#F48FB1",
		background: "#FFF7FB",
		text_primary: "#AD1457",
		text_secondary: "#C2185B",
		text_third: "#fff",
		font_primary: "'Poppins', sans-serif",
		font_secondary: "'Montserrat', sans-serif",
		color_adm: '#f2f2f2',
		color_text: '#333',

		page_construct_background: '#000',
		page_construct_color: '#fff',
		page_construct_accent: '#ED3237'
	},
	{
		name: "Cinza",
		primary: "#607d8b",
		secondary: "#BDBDBD",
		accent: "#E0E0E0",
		background: "#F9F9F9",
		text_primary: "#424242",
		text_secondary: "#9E9E9E",
		text_third: "#fff",
		font_primary: "'Ubuntu', sans-serif",
		font_secondary: "'Helvetica', sans-serif",
		color_adm: '#f2f2f2',
		color_text: '#333',

		page_construct_background: '#000',
		page_construct_color: '#fff',
		page_construct_accent: '#ED3237',
	},
	{
		name: "Laranja",
		primary: "#FF7043",
		secondary: "#FFA726",
		accent: "#FFD180",
		background: "#FFF9F4",
		text_primary: "#BF360C",
		text_secondary: "#FF8A65",
		text_third: "#fff",
		font_primary: "'Quicksand', sans-serif",
		font_secondary: "'Roboto', sans-serif",
		color_adm: '#f2f2f2',
		color_text: '#333',

		page_construct_background: '#000',
		page_construct_color: '#fff',
		page_construct_accent: '#ED3237'
	},
	{
		name: "Vinho",
		primary: "#4A001F",
		secondary: "#800020",
		accent: "#D32F2F",
		background: "#FFFAFA",
		text_primary: "#330015",
		text_secondary: "#A05252",
		text_third: "#fff",
		font_primary: "'Quicksand', sans-serif",
		font_secondary: "'Roboto', sans-serif",
		color_adm: '#f2f2f2',
		color_text: '#333',

		page_construct_background: '#000',
		page_construct_color: '#fff',
		page_construct_accent: '#ED3237'
	},
	{
		name: "Verde",
		primary: "#4CAF50",
		secondary: "#A5D6A7",
		accent: "#81C784",
		background: "#F7FCF7",
		text_primary: "#2E7D32",
		text_secondary: "#66BB6A",
		text_third: "#fff",
		font_primary: "'Ubuntu', sans-serif",
		font_secondary: "'Helvetica', sans-serif",
		color_adm: '#f2f2f2',
		color_text: '#333',

		page_construct_background: '#000',
		page_construct_color: '#fff',
		page_construct_accent: '#ED3237'
	},
	{
		name: "Gold",
		primary: "#004992",
		secondary: "#2b3c51",
		accent: "#fba91f",
		background: "#F7FCF7",
		text_primary: "#004992",
		text_secondary: "#323232",
		text_third: "#fff",
		font_primary: "'Ubuntu', sans-serif",
		font_secondary: "'Helvetica', sans-serif",
		color_adm: '#f2f2f2',
		color_text: '#333',

		page_construct_background: '#000',
		page_construct_color: '#fff',
		page_construct_accent: '#ED3237'
	},
];
